# Generated by Django 2.2.9 on 2022-01-26 05:52

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[employee.models.validate_name])),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=30, unique=True, validators=[employee.models.validate_email])),
                ('role', models.CharField(default='Guest', max_length=30)),
                ('phone_num', models.BigIntegerField(unique=True)),
                ('joiningDate', models.DateField()),
                ('address', models.CharField(default='Y', max_length=255)),
            ],
            options={
                'db_table': 'employee_master',
                'ordering': ['role'],
            },
        ),
    ]
